name: Release & Publish

on:
  push:
    tags:
      - 'v*'

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: 'https://npm.pkg.github.com/simondotm'
          #scope: '@simondotm'
      #- run: npm run addscope

      - name: Build plugin
        run: npx nx build nxfirebase

      - name: Create package
        run: npm pack
        working-directory: ./dist/packages/nxfirebase

      - name: Publish to GitHub Packages
        run: npm publish
        working-directory: ./dist/packages/nxfirebase
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: publish
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
